### ISSUE TITLE
Create the player 

### ISSUE THREAD

**Issue by Kavignon** [Kavignon/CircleOfLyfe#1]
The player should have 
Basic elements for moving inside the world
Should be able to collect collectibles 
Can transform into his/her totems collected during the course of the game

**Comment by gamezter** [comment]
the player has multiple steps:
egg->moose->child->fish->teen->eagle->adult->phoenix->elder/shaman

**Comment by Kavignon** [comment]
make an enum to represent the different stages for code handling later

**Comment by nemotime** [comment]
once you get back I can show you what I have, almost done

**Comment by Kavignon** [comment]
Fix issues with code with the script ShamanApprentice. 
More readable and easier to understand.
